spring:
  application:
    name: server
    desc: SpringCloud server project
    version: 4.0.0
    packageName: com.aaron
  datasource:
    url: jdbc:mysql://localhost:3306/db_server?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 11111111
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: admin
    password: password

grpc:
  server:
    port: 9001
  consul:
    discovery:
      tags: grpc,dev


